version: "3.5"

services:
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_DATABASE: $DATABASE_NAME
            MONGO_INITDB_ROOT_USERNAME: $DATABASE_USER
            MONGO_INITDB_ROOT_PASSWORD: $DATABASE_PASSWORD
        restart: unless-stopped
    
    sender:
        build: .
        links:
            - mongo
        depends_on:
            - mongo
        environment:
            ENVIRONMENT: $ENVIRONMENT
            DATABASE_NAME: $DATABASE_NAME
            DATABASE_HOST: $DATABASE_HOST
            DATABASE_PORT: $DATABASE_PORT
            DATABASE_USER: $DATABASE_USER
            DATABASE_PASSWORD: $DATABASE_PASSWORD
            BACKUP_SLEEP: $BACKUP_SLEEP
            BACKUP_DAYS: $BACKUP_DAYS
            BACKUP_SECRET: $BACKUP_SECRET
            S3_ACCESS_KEY: $S3_ACCESS_KEY
            S3_SECRET_KEY: $S3_SECRET_KEY
            S3_REGION: $S3_REGION
            S3_BUCKET: $S3_BUCKET
        volumes:
            - ./backups:/backups
            - ./restore:/restore
        restart: unless-stopped

    mongoexpress:
        image: mongo-express
        depends_on:
            - mongo
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: $DATABASE_HOST
            ME_CONFIG_MONGODB_PORT: $DATABASE_PORT
            ME_CONFIG_MONGODB_ADMINUSERNAME: $DATABASE_USER
            ME_CONFIG_MONGODB_ADMINPASSWORD: $DATABASE_PASSWORD
        restart: unless-stopped
    
